version: "3"
services:
  backend:
    build:
      context: ./yojak-erp-backend
      dockerfile: Dockerfile
    working_dir: /yojak
    
    env_file:
      - ./yojak-erp-backend/.env
    volumes:
        - ./yojak-erp-backend:/yojak
    expose:
      - 8023
    ports:
      - "8023:8023"
    restart: always
   
  app:
    build:
      context: ./yojak-erp-frontend
      dockerfile: Dockerfile
    working_dir: /app
    
    ports:
      - "6969:6969"
    expose:
      - 6969